[package]
name = "cl_plotter"
version = "0.1.0"
authors = ["ju851bah <julian@bahner.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9.3"
terminal_size = "0.1.12"
